### ISSUE TITLE
xmlLoader throws loader error in nw.js (formerly node-webkit)

### ISSUE THREAD

**Issue by pchertok** [massiveinteractive/mloader#24] opened 2015-04-09 20:00 UTC
If you use xmlLoader in nw.js - it will throw "Http 0" error.  If you use the inspector tools to monitor the network traffic, the files does get loaded into the application (browser) with no errors.

**Comment by dpeek** [comment] 2015-04-10 09:53
Have you tested this with just a plain `haxe.Http` as well? I think the problem is that local file requests (ie `file:///`) return status 0 when they complete, which `haxe.Http` considers an error.

Actually it looks like this has been fixed already in Std: https://github.com/HaxeFoundation/haxe/issues/2075

So, maybe try with 3.2 rc?

**Comment by dpeek** [comment] 2015-04-13 09:31
Closing for now, let me know if this is still a problem on 3.2rc

**Closed by dpeek** 2015-04-13 09:31 UTC

**Comment by pchertok** [comment] 2015-04-13 18:15
haxe 3.2.-rc2 does fix the issue - thanks for looking into it.  Great set of libraries by the way - made the as3 -> haxe transition much easier.
